name: NPM Release

on:
  release:
    types: [released]

jobs:
  publish:
    name: Build & Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Set version
        run: npm version --no-git-tag-version ${{github.event.release.tag_name}}

      - name: npm pack
        run: npm pack

      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: "eng-automation-testing-*.tgz"

      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/paritytech/npm_publish_automation/actions/workflows/publish.yml/dispatches
          ref: main
          inputs: '${{ format(''{{ "repo": "{0}", "run_id": "{1}" }}'', github.repository, github.run_id) }}'
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_PUBLISH_AUTOMATION_TOKEN }}
