name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The tag's version (numeric part only)
        required: true

jobs:
  opstooling-testing-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to push the tag to the repository
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Release
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions"
          git add --force dist
          git commit -m v${{ github.event.inputs.version }}
          git tag v${{ github.event.inputs.version }}
          git push origin v${{ github.event.inputs.version }}
